[WIP] Readme revamp
AbsaOSS/k8gb pull request #179
Opened 2020-10-24 16:26 UTC by ytsarev

* Splitting to sections
* Create placeholders for important enhancements

2020-10-24 16:29 UTC, ytsarev commented
guys, it is WIP, would love to get early feedback on the overall direction with docs

@somaritane it's inline on what we discussed in person
@donovanmuller I reused the abstract from your brilliant kubecon talk proposal
@k0da @kuritka dudes, any feedback/ideas is highly appreciated

2020-10-26 09:03 UTC, kuritka requested changes
nice...! 

_*I found some minimal typos_

2020-10-26 09:03 UTC, kuritka commented on docs/local.md
> +Both clusters have [podinfo](https://github.com/stefanprodan/podinfo) installed on the top where each
```suggestion
Both clusters have [podinfo](https://github.com/stefanprodan/podinfo) installed on the top, where each
```

2020-10-26 09:18 UTC, ytsarev commented on README.md
> +* Load balancing is based on timeproof DNS protocol which is perfect for global scope and extremely reliable
@kuritka not sure here, used as adjective  https://en.wiktionary.org/wiki/timeproof . @donovanmuller please comment as a native speaker, thanks

2020-10-26 09:21 UTC, ytsarev commented
@kuritka cool stuff, thanks a ton for review

2020-10-26 12:39 UTC, k0da approved these changes
LGTM

2020-10-26 12:50 UTC, donovanmuller approved these changes

2020-10-26 12:52 UTC, kuritka approved these changes

2020-10-26 13:22 UTC, merged

2021-05-04 15:54 UTC, tammersaleh commented on README.md
> +* Load balancing is based on timeproof DNS protocol which is perfect for global scope and extremely reliable
Hey @ytsarev - is there anything we can link to that describes the DNS timeproof protocol?  Google is failing me.