Admiralty integration tutorial
AbsaOSS/k8gb pull request #213
Opened 2020-12-07 05:29 UTC by ytsarev

Provides short demo local setup of k8gb working
together with admiralty.io

2020-12-07 08:05 UTC, donovanmuller submitted a review, later dismissed

2020-12-07 08:12 UTC, kuritka approved these changes

2020-12-07 08:25 UTC, k0da approved these changes
lgtm

2020-12-07 11:11 UTC, somaritane requested changes
lgtm, just several small fixes ahead.

2020-12-07 11:11 UTC, somaritane commented on docs/admiralty.md
> +Observe that associated Ingress has also followed the Pods to the Target clusters
```suggestion
Observe that associated Ingress has also followed the Pods to the target clusters
```

2020-12-07 11:11 UTC, somaritane commented on docs/admiralty.md
> +Observer that there are no Gslb resources in the Target clusters
```suggestion
Observer that there are no Gslb resources in the target clusters
```

2020-12-07 11:11 UTC, somaritane commented on docs/admiralty.md
> +Add k8gb strategy annotation to the Ingress object in the Source cluster
```suggestion
Add k8gb strategy annotation to the Ingress object in the source cluster
```

2020-12-07 11:11 UTC, somaritane commented on docs/admiralty.md
> +Edit `podinfo` Deployment to add admiralty `multicluster.admiralty.io/elect` scheduling Annotation to Pod spec template
```suggestion
Edit `podinfo` Deployment to add Admiralty `multicluster.admiralty.io/elect` scheduling Annotation to Pod spec template
```

2020-12-07 11:19 UTC, ytsarev commented on docs/admiralty.md
> +kubectl --context kind-eu create ns k8gb
@somaritane it all based on https://admiralty.io/docs/quick_start/ as a prerquisite and kind is there

2020-12-07 11:21 UTC, ytsarev commented on docs/admiralty.md
> +Observe that pods were scheduled to Target cluster after then Annotation patch
or maybe vice versa for capital? As for
```
apiVersion: multicluster.admiralty.io/v1alpha1
kind: Target

```

2020-12-07 11:26 UTC, somaritane commented on docs/admiralty.md
> +kubectl --context kind-eu create ns k8gb
Ah, didn't notice!

2020-12-07 11:27 UTC, somaritane commented on docs/admiralty.md
> +Observe that pods were scheduled to Target cluster after then Annotation patch
sure thing, just needs to be capital everywhere for consistency 👍

2020-12-07 15:52 UTC, ytsarev commented
@somaritane thanks a ton for the thorough review, please check again

2020-12-07 16:05 UTC, somaritane approved these changes
lgtm!

2020-12-14 12:00 UTC, kuritka approved these changes

2020-12-14 12:40 UTC, somaritane approved these changes
lgtm

2020-12-16 08:53 UTC, ytsarev commented
https://github.com/admiraltyio/admiralty/releases/tag/v0.13.2 ingress annotation trigger released so we can merge this doc

2020-12-16 08:54 UTC, merged