Enable docker multiarch build
AbsaOSS/k8gb pull request #267
Opened 2021-01-25 16:50 UTC by k0da

Build docker image for aarch64 and combine them into a single manifest

Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

2021-01-25 16:52 UTC, k0da commented
fixes https://github.com/AbsaOSS/k8gb/issues/243

2021-01-25 17:12 UTC, ytsarev commented on Makefile
> +	docker manifest annotate ${IMG} ${IMG}-arm64 \
amd64 doesn't require annotation ?

2021-01-25 17:14 UTC, k0da commented on Makefile
> +	docker manifest annotate ${IMG} ${IMG}-arm64 \
No, amd64 is a default

2021-01-25 17:24 UTC, ytsarev requested changes

2021-01-25 17:24 UTC, ytsarev commented on Makefile
> +	$(call docker-push-arch arm64)
```suggestion
	$(call docker-push-arch, arm64)
```

2021-01-25 17:24 UTC, ytsarev commented on Makefile
> +	$(call docker-push-arch amd64)
```suggestion
	$(call docker-push-arch,amd64)
```

2021-02-02 07:30 UTC, ytsarev requested changes
@k0da can we keep amd64 optional under flag? the local build of it is extremely resource-demanding

2021-02-04 21:02 UTC, ytsarev approved these changes

2021-02-04 21:03 UTC, merged