Switch sed to helm template
AbsaOSS/k8gb pull request #294
Opened 2021-02-12 11:49 UTC by k0da

Wrap gslb test resources with dummy helm, in oder to leverage helm
template engine and get rid of gnused requirement on Mac

Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

2021-02-12 12:14 UTC, somaritane approved these changes
lgtm 👍 , we shouldn't expect users to use certain sed package.

2021-02-15 09:47 UTC, ytsarev commented
the integration tests are dependant on the location of the templates

2021-02-15 09:47 UTC, ytsarev requested changes
As the comment above

2021-02-15 10:40 UTC, k0da commented
sure, I need to rethink it a little bit more.

2021-02-17 09:51 UTC, closed without merging