Bring back external-dns service account
AbsaOSS/k8gb pull request #329
Opened 2021-02-28 19:40 UTC by k0da

During CoreDNS refactor https://github.com/AbsaOSS/k8gb/pull/292
local external-dns instance was removed, while Route53 and NS1
external-dns instances relies on service account created by local
instance. This commit brings back external-dns service account.

Fixes: https://github.com/AbsaOSS/k8gb/issues/328

Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

2021-02-28 21:05 UTC, somaritane requested changes
Do we still need this ServiceAccount for cases when absaoss/k8s_crd CoreDNS plugin is used instead of local external-dns? 
If not, maybe SA template should be made optional for such cases?

2021-03-01 07:32 UTC, ytsarev requested changes
I think we also need to return ClusterRole and ClusterRoleBinding https://github.com/AbsaOSS/k8gb/pull/292/files#diff-9519c8095c65b9bc934732e5b724b7ebfa3c792a96ac9e6a8037adeaa9ad26ecR3

2021-03-01 08:48 UTC, ytsarev requested changes
```
time="2021-03-01T08:47:03Z" level=debug msg="Considering zone: /hostedzone/Z1026666KUI3QVMMU5ZI (domain: k8gb.io.)"
time="2021-03-01T08:47:03Z" level=error msg="dnsendpoints.externaldns.k8s.io is forbidden: User \"system:serviceaccount:k8gb:external-dns\" cannot list resource \"dnsendpoints\" in API group \"externaldns.k8s.io\" at the cluster scope"
```
We definitely need to return RBAC part

2021-03-01 08:57 UTC, ytsarev commented
@k0da i've amended PR

2021-03-01 09:03 UTC, ytsarev commented
@somaritane thinking of condition for route53 and ns1? Makes sense, though I don't like the idea of listing all external-dns based edgeDNS providers explicitly. Make it inverse for Infoblox condition?

2021-03-01 09:09 UTC, k0da commented
Do we need ingresses, pods and services for external-dns? IIUC we're only insterested in DNSEndpoint object

2021-03-01 09:13 UTC, ytsarev commented
@k0da good point, current conf was just took from the upstream. We can strict it down to DNSEndpoints

2021-03-01 09:25 UTC, k0da commented
also verbs should be limited to get, read only.

2021-03-01 09:54 UTC, somaritane commented
> @somaritane thinking of condition for route53 and ns1? Makes sense, though I don't like the idea of listing all external-dns based edgeDNS providers explicitly. Make it inverse for Infoblox condition?

@ytsarev, definitely should not list external-dns providers as there going to be more. 
Thinking about Infoblox in condition, is it going to be the only case where we use k8s_crd CoreDNS plugin instead of local external-dns?

2021-03-01 09:58 UTC, ytsarev commented
@somaritane slight misunderstanding here it seems. We are using coredns crd plugin in *every* case. It replaces the previous setup of local external-dns+etcd. In the case of infoblox we just don't use external-dns+infoblox-provider given its limitations and interacting with Infoblox api directly with k8gb. Will it be the only case of direct API integration is an open question as the external-dns providers heavily deviate from a quality standpoint.

2021-03-01 10:07 UTC, ytsarev commented
@somaritane so the ClusterRole reasonably became pretty much read-only for DNSEndpoints. In this case we can neglect additional conditions IMHO and simply install it every time

2021-03-01 10:07 UTC, somaritane commented
@ytsarev I see now. In this case let's make rbac template created only in case if Infoblox provider is not enabled, so we don't create entities we're not going to use in cluster.

2021-03-01 10:07 UTC, ytsarev approved these changes

2021-03-01 10:13 UTC, ytsarev commented
@somaritane but it's vulnerable to the same scenario. If we add second non external-dns based edgeDNS we will have to list it. It's more burden than having 3 unused security fine rbac entities in the cluster

2021-03-01 10:28 UTC, somaritane commented
@ytsarev makes sense.

2021-03-01 10:28 UTC, somaritane approved these changes
lgtm

2021-03-01 10:32 UTC, merged