Serve specific zone by CoreDNS
AbsaOSS/k8gb pull request #420
Opened 2021-04-01 08:47 UTC by k0da

Serving . could lead into long resolves. Especially while service A
record only and alpine based workloads do both AAAA and A queries.

Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

2021-04-01 10:35 UTC, ytsarev reviewed
Before we merge it - could you please check the yaml anchor propagation in ArgoCD context? I recall some issues with it before we switched to `.` in coredns

2021-04-06 09:31 UTC, k0da commented
@ytsarev Argo can serve it through metachart

2021-04-06 13:54 UTC, kuritka approved these changes

2021-04-06 14:25 UTC, ytsarev commented
@k0da okay, but will it work here https://github.com/bison-cloud-platform/bks-registry/tree/master/argocd/k8gb ?

2021-04-08 07:39 UTC, somaritane commented
> @k0da okay, but will it work here https://github.com/bison-cloud-platform/bks-registry/tree/master/argocd/k8gb ?

@ytsarev, we're talking about default chart values here, project using k8gb helm chart can always fallback to dnsZone duplication in their custom values, if there are any issues with anchor annotation.

2021-04-08 07:39 UTC, somaritane approved these changes

2021-04-09 15:03 UTC, ytsarev commented
@somaritane yes, but in existing argo configuration with the removal of `.` default and not working yaml anchoring the coredns configuration will config empty value for the zone breaking existing configuration completely.

So I still suggest testing the actual behavior with the existing argo-based deployments as the coredns zone parameter is not overlayed there at the moment.

2021-04-09 15:24 UTC, k0da commented
@ytsarev it have its own values and fixed chart version. This merge won't break it.

2021-04-09 15:33 UTC, ytsarev requested changes
@k0da it doesn't have its own value for coredns zone. It is not overlayed either. If we merge it right now - we forget about it and the future upgrade will potentially break our argo based artifactory deployments.

It will also make the case of undocumented requirement of explicit override of coredns zone in argocd context which will deviate from standard helm installation.

So please check it.

2021-04-09 15:36 UTC, somaritane commented
> @somaritane yes, but in existing argo configuration with the removal of `.` default and not working yaml anchoring the coredns configuration will config empty value for the zone breaking existing configuration completely.
> 
> So I still suggest testing the actual behavior with the existing argo-based deployments as the coredns zone parameter is not overlayed there at the moment.

@ytsarev makes sense.

2021-04-13 12:21 UTC, closed without merging