FIX: Annotate and Label existing DNSEndpoints
AbsaOSS/k8gb pull request #443
Opened 2021-04-14 15:44 UTC by k0da

When upgrading from 0.7.5 to 0.7.6 new generated objectmeta wasn't
concidered during DNSEndpoint reconcilation. Fix this by respecting
computed Labels and Annotations while reconciling DNSEndpoint.

fixes https://github.com/AbsaOSS/k8gb/issues/324

Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

2021-04-14 22:22 UTC, ytsarev requested changes
Looks great, just a small suggestion re assert failure output

2021-04-14 22:22 UTC, ytsarev commented on controllers/gslb_controller_test.go
> +	assert.Equal(t, want, got, "got:\n %q annotation value,\n\n want:\n %q", got, want, got, want)
```suggestion
	assert.Equal(t, want, got, "got:\n %q annotation value,\n\n want:\n %q", got, want)
```

2021-04-14 22:26 UTC, k0da commented on controllers/gslb_controller_test.go
> +	assert.Equal(t, want, got, "got:\n %q annotation value,\n\n want:\n %q", got, want, got, want)
@ytsarev thanks, amended

2021-04-15 12:23 UTC, ytsarev approved these changes

2021-04-15 12:29 UTC, merged