Don't reconcile Infoblox immediately when creating zone delegation fails
AbsaOSS/k8gb pull request #462
Opened 2021-05-03 09:55 UTC by kuritka

At the moment we have 1 connection + timeout 10s to Infoblox. Infoblox connection fails (error), so reconciliation loop reset immediately (I'm assuming +/- 2s).

k8gb can’t connect because Infoblox is constantly under load of waiting connections, so loop for single GSLB looks like this:
`10s (timeout error) + 2s (recover) + 10s (timeout error) + 2s (recover) + 10s + 2s,….`

`RECONCILE_REQUEUE_SECONDS` defines the period of reconciliation loop. If we don't error and wait until reconciliation period passes, the loop for single GSLB will look like:  `10s (timeout) + 50s (recover) + 10s (timeout) + 50s (recover)…`

50s recover looks much better, because there is more space for other connections to do their job release space for waiting connections. In addition, it doesn't produce such amount of timeout errors.

Signed-off-by: kuritka <kuritka@gmail.com>

2021-05-04 09:48 UTC, somaritane commented on controllers/gslb_controller.go
> +		if r.Config.EdgeDNSType == depresolver.DNSTypeInfoblox {
Do we want provider-specific logic to be in that package?

2021-05-04 09:59 UTC, somaritane commented
@kuritka I feel like we're trying to solve the situation with a particular provider and local environment limitations in the upstream project. This might potentially impact users in the future. Probably we should make this change in the reconciliation loop optional for that provider, with the respective option flag. WDYT?

2021-05-04 14:00 UTC, kuritka commented
@somaritane , updated. The change is independent on provider.

2021-05-05 16:10 UTC, somaritane reviewed
> @somaritane , updated. The change is independent on provider.

@kuritka cool, let's amend the commit message and PR to make them consistent with changes.

2021-05-05 16:16 UTC, somaritane requested changes

2021-05-05 16:16 UTC, somaritane commented on controllers/gslb_controller.go
> +		log.Err(err).Msg("Create zone delegation")
```suggestion
		log.Err(err).Msg("Unable to create zone delegation")
```

2021-05-05 16:19 UTC, kuritka commented on controllers/gslb_controller.go
> +		log.Err(err).Msg("Create zone delegation")
@somaritane , message updated

2021-05-06 07:47 UTC, somaritane approved these changes

2021-05-06 07:50 UTC, somaritane commented
@kuritka LGTM 👍

2021-05-06 08:45 UTC, kuritka commented
@ytsarev, does this go to v0.8.0 ?

2021-05-06 08:48 UTC, ytsarev approved these changes

2021-05-06 08:48 UTC, ytsarev commented
@kuritka sure :)

2021-05-06 08:49 UTC, merged